import json
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, Table, TableStyle
)
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from mermaid_render import render_mermaid_to_png
from reportlab.platypus import Image as RLImage
import os


def _load(project):
    try:
        analysis = json.loads(project.analysis_json) if project.analysis_json else {}
    except Exception:
        analysis = {}
    try:
        api_spec = json.loads(project.api_spec_json) if project.api_spec_json else None
    except Exception:
        api_spec = None
    try:
        tech_stack = json.loads(project.tech_stack_json) if project.tech_stack_json else None
    except Exception:
        tech_stack = None
    try:
        planning = json.loads(project.planning_json) if project.planning_json else None
    except Exception:
        planning = None
    try:
        traceability = json.loads(project.traceability_json) if getattr(project, "traceability_json", None) else None
    except Exception:
        traceability = None
    return analysis, api_spec, tech_stack, planning, traceability


# ---------------- PDF EXPORT ----------------

def generate_pdf(project) -> BytesIO:
    analysis, api_spec, tech_stack, planning, traceability = _load(project)

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                             topMargin=0.8 * inch, bottomMargin=0.8 * inch,
                             leftMargin=0.8 * inch, rightMargin=0.8 * inch)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=22, spaceAfter=6)
    sub_style = ParagraphStyle("SubX", parent=styles["Normal"], fontSize=10, textColor=colors.HexColor("#2B5C87"), spaceAfter=18)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor("#182333"), spaceBefore=16, spaceAfter=8)
    body = ParagraphStyle("BodyX", parent=styles["Normal"], fontSize=10.3, leading=15)

    elements = []
    elements.append(Paragraph(project.title, title_style))
    elements.append(Paragraph("Software Requirement Specification — Generated by AI Software Requirement Engineer", sub_style))

    elements.append(Paragraph("1. Description", h2))
    elements.append(Paragraph(project.description, body))

    if analysis:
        elements.append(Paragraph("2. Objectives", h2))
        elements.append(ListFlowable(
            [ListItem(Paragraph(o, body)) for o in analysis.get("objectives", [])], bulletType="bullet"))

        elements.append(Paragraph("3. Scope", h2))
        elements.append(Paragraph(analysis.get("scope", ""), body))

        elements.append(Paragraph("4. Target Users", h2))
        elements.append(Paragraph(", ".join(analysis.get("target_users", [])), body))

        elements.append(Paragraph("5. Functional Requirements", h2))
        elements.append(ListFlowable(
            [ListItem(Paragraph(r, body)) for r in analysis.get("functional_requirements", [])], bulletType="bullet"))

        elements.append(Paragraph("6. Non-Functional Requirements", h2))
        elements.append(ListFlowable(
            [ListItem(Paragraph(r, body)) for r in analysis.get("non_functional_requirements", [])], bulletType="bullet"))

        elements.append(Paragraph("7. Constraints", h2))
        elements.append(ListFlowable(
            [ListItem(Paragraph(c, body)) for c in analysis.get("constraints", [])], bulletType="bullet"))

        elements.append(Paragraph("8. Assumptions", h2))
        elements.append(ListFlowable(
            [ListItem(Paragraph(a, body)) for a in analysis.get("assumptions", [])], bulletType="bullet"))

    try:
        diagrams = json.loads(project.diagrams_json) if project.diagrams_json else None
    except Exception:
        diagrams = None
    temp_files = []
    if diagrams:
        elements.append(Paragraph("9. UML Diagrams", h2))
        diagram_labels = [
            ("use_case_diagram", "Use Case Diagram"),
            ("class_diagram", "Class Diagram"),
            ("er_diagram", "Entity Relationship Diagram"),
        ]
        for key, label in diagram_labels:
            code = diagrams.get(key)
            if not code:
                continue
            png_path = render_mermaid_to_png(code)
            if png_path:
                elements.append(Paragraph(label, ParagraphStyle("H3", parent=h2, fontSize=11.5, spaceBefore=10)))
                elements.append(RLImage(png_path, width=5.5 * inch, height=3.5 * inch, kind="proportional"))
                elements.append(Spacer(1, 10))
                temp_files.append(png_path)

    if api_spec:
        elements.append(Paragraph("10. API Specification", h2))
        for ep in api_spec.get("endpoints", []):
            elements.append(Paragraph(f"<b>{ep['method']}</b> {ep['path']} — {ep['description']}", body))
            elements.append(Spacer(1, 4))

    if tech_stack:
        elements.append(Paragraph("11. Technology Stack", h2))
        rows = [["Category", "Technology", "Reason"]]
        for cat in ["frontend", "backend", "database", "cloud_deployment"]:
            item = tech_stack.get(cat, {})
            rows.append([cat.replace("_", " ").title(), item.get("technology", ""), item.get("reason", "")])
        table = Table(rows, colWidths=[1.3 * inch, 1.4 * inch, 3.3 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#182333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDE3E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(table)

    if planning:
        elements.append(Paragraph("12. Project Plan", h2))
        elements.append(Paragraph(f"Estimated duration: {planning.get('estimated_duration_weeks', '?')} weeks", body))
        elements.append(Spacer(1, 6))
        for m in planning.get("milestones", []):
            elements.append(Paragraph(f"<b>{m['name']}</b> — {m['description']}", body))

        elements.append(Paragraph("Risks", ParagraphStyle("H3", parent=h2, fontSize=11.5, spaceBefore=10)))
        for r in planning.get("risks", []):
            elements.append(Paragraph(f"<b>[{r['impact']}]</b> {r['risk']} — <i>Mitigation:</i> {r['mitigation']}", body))
            elements.append(Spacer(1, 4))

    if traceability:
        elements.append(Paragraph("13. Requirements Traceability & Validation", h2))
        comp_score = traceability.get("completeness_score", "")
        comp_pct = traceability.get("completeness_percentage", 0)
        elements.append(Paragraph(f"<b>Completeness:</b> {comp_score} ({comp_pct}% coverage)", body))
        val_sum = traceability.get("validation_summary", "")
        if val_sum:
            elements.append(Paragraph(f"<b>Validation Summary:</b> {val_sum}", body))
        elements.append(Spacer(1, 6))

        matrix_rows = [["ID", "Functional Requirement", "UML Diagram(s)", "API Endpoint(s)", "Status"]]
        for item in traceability.get("items", []):
            req_id = item.get("requirement_id", "")
            req_text = item.get("requirement_text", "")
            diag_text = ", ".join(item.get("diagram_elements", [])) or "None"
            api_text = ", ".join(item.get("api_endpoints", [])) or "None"
            status_text = item.get("status", "").replace("_", " ").title()
            matrix_rows.append([
                Paragraph(f"<b>{req_id}</b>", ParagraphStyle("TID", parent=body, fontSize=8, leading=10)),
                Paragraph(req_text, ParagraphStyle("TReq", parent=body, fontSize=8, leading=10)),
                Paragraph(diag_text, ParagraphStyle("TDiag", parent=body, fontSize=8, leading=10)),
                Paragraph(api_text, ParagraphStyle("TApi", parent=body, fontSize=8, leading=10)),
                Paragraph(status_text, ParagraphStyle("TStat", parent=body, fontSize=8, leading=10)),
            ])
        m_table = Table(matrix_rows, colWidths=[0.8 * inch, 2.0 * inch, 1.4 * inch, 1.3 * inch, 1.0 * inch])
        m_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#182333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDE3E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(m_table)
        elements.append(Spacer(1, 10))

    doc.build(elements)
    for f in temp_files:
        if os.path.exists(f):
            os.remove(f)
    buffer.seek(0)
    return buffer


# ---------------- DOCX EXPORT ----------------

def generate_docx(project) -> BytesIO:
    analysis, api_spec, tech_stack, planning, traceability = _load(project)

    doc = DocxDocument()

    title = doc.add_heading(project.title, level=0)
    sub = doc.add_paragraph("Software Requirement Specification — Generated by AI Software Requirement Engineer")
    sub.runs[0].italic = True

    doc.add_heading("1. Description", level=1)
    doc.add_paragraph(project.description)

    if analysis:
        doc.add_heading("2. Objectives", level=1)
        for o in analysis.get("objectives", []):
            doc.add_paragraph(o, style="List Bullet")

        doc.add_heading("3. Scope", level=1)
        doc.add_paragraph(analysis.get("scope", ""))

        doc.add_heading("4. Target Users", level=1)
        doc.add_paragraph(", ".join(analysis.get("target_users", [])))

        doc.add_heading("5. Functional Requirements", level=1)
        for r in analysis.get("functional_requirements", []):
            doc.add_paragraph(r, style="List Bullet")

        doc.add_heading("6. Non-Functional Requirements", level=1)
        for r in analysis.get("non_functional_requirements", []):
            doc.add_paragraph(r, style="List Bullet")

        doc.add_heading("7. Constraints", level=1)
        for c in analysis.get("constraints", []):
            doc.add_paragraph(c, style="List Bullet")

        doc.add_heading("8. Assumptions", level=1)
        for a in analysis.get("assumptions", []):
            doc.add_paragraph(a, style="List Bullet")

    diagrams = json.loads(project.diagrams_json) if project.diagrams_json else None
    if diagrams:
        doc.add_heading("9. UML Diagrams", level=1)
        diagram_labels = [
            ("use_case_diagram", "Use Case Diagram"),
            ("class_diagram", "Class Diagram"),
            ("er_diagram", "Entity Relationship Diagram"),
        ]
        for key, label in diagram_labels:
            code = diagrams.get(key)
            if not code:
                continue
            png_path = render_mermaid_to_png(code)
            if png_path:
                doc.add_heading(label, level=2)
                doc.add_picture(png_path, width=Inches(6))
                os.remove(png_path)

    if api_spec:
        doc.add_heading("10. API Specification", level=1)
        for ep in api_spec.get("endpoints", []):
            p = doc.add_paragraph()
            p.add_run(f"{ep['method']} ").bold = True
            p.add_run(f"{ep['path']} — {ep['description']}")

    if tech_stack:
        doc.add_heading("11. Technology Stack", level=1)
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text = "Category", "Technology", "Reason"
        for cat in ["frontend", "backend", "database", "cloud_deployment"]:
            item = tech_stack.get(cat, {})
            row = table.add_row().cells
            row[0].text = cat.replace("_", " ").title()
            row[1].text = item.get("technology", "")
            row[2].text = item.get("reason", "")

    if planning:
        doc.add_heading("12. Project Plan", level=1)
        doc.add_paragraph(f"Estimated duration: {planning.get('estimated_duration_weeks', '?')} weeks")
        doc.add_heading("Milestones", level=2)
        for m in planning.get("milestones", []):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"{m['name']}: ").bold = True
            p.add_run(m["description"])

        doc.add_heading("Risks", level=2)
        for r in planning.get("risks", []):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"[{r['impact']}] ").bold = True
            p.add_run(f"{r['risk']} — Mitigation: {r['mitigation']}")

    if traceability:
        doc.add_heading("13. Requirements Traceability & Validation", level=1)
        comp_score = traceability.get("completeness_score", "")
        comp_pct = traceability.get("completeness_percentage", 0)
        doc.add_paragraph(f"Completeness: {comp_score} ({comp_pct}% coverage)")
        val_sum = traceability.get("validation_summary", "")
        if val_sum:
            doc.add_paragraph(f"Validation Summary: {val_sum}")

        table = doc.add_table(rows=1, cols=5)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text, hdr[4].text = "ID", "Requirement", "Diagram Elements", "API Endpoints", "Status"
        for item in traceability.get("items", []):
            row = table.add_row().cells
            row[0].text = item.get("requirement_id", "")
            row[1].text = item.get("requirement_text", "")
            row[2].text = ", ".join(item.get("diagram_elements", [])) or "None"
            row[3].text = ", ".join(item.get("api_endpoints", [])) or "None"
            row[4].text = item.get("status", "").replace("_", " ").title()

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer